export const POSTS_LOADED_SUCCESS = "POSTS_LOADED_SUCCESS";
export const POSTS_LOADED_FAIL = "POSTS_LOADED_FAIL";
export const CREATE_POST = "CREATE_POST";

export const POSTLIKE_SUCCESS = "POSTLIKE_SUCCESS";
export const POSTUNLIKE_SUCCESS = "POSTUNLIKE_SUCCESS";

export const SHOW_LOGIN_PANEL = "SHOW_LOGIN_PANEL";

export const POSTSBYID_LOADED_SUCCESS = "POSTSBYID_LOADED_SUCCESS";